LINK           = g++
LIBS          = -L/usr/lib

SOURCES       = tree_gen.cpp
TARGET        = tree_gen

first: $(TARGET)

$(TARGET): $(SOURCES)
	$(LINK) -o $(TARGET) $(SOURCES) $(LIBS)
clean: 
	rm *.o
	rm $(TARGET)


